### ISSUE TITLE
not working on drone 0.4

### ISSUE THREAD

**Issue by nemonweb** [gtaylor/drone-hipchat#1]
responds [fatal] Error parsing the .drone.yml

what need to do?

**Comment by brgaulin** [comment]
I was able to get this working with drone 0.4 latest:
```
notify:
  hipchat:
    from: Drone
    notify: true
    room_id_or_name: room_here
    auth_token: v2_auth_token_here
```

YAML is whitespace sensitive so make sure the notify line has no space before it, then do 2 space indentation on each line.
